# Generated by Django 5.2.7 on 2026-01-05 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskMaster', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoo',
            old_name='srno',
            new_name='id',
        ),
    ]
